# Generated by Django 4.0.6 on 2022-07-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='stoe_custom_last_na_dedd0c_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='stoe_customers',
        ),
    ]
