# Generated by Django 4.0.6 on 2022-07-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ( 'collection1')
            ""","""
            DELETE FROM store_collection
            WHERE title='collection1'
            """),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),

    ]
