# Generated by Django 4.0.6 on 2022-07-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_feature_product_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updeate',
            new_name='last_update',
        ),
    ]
